source('modules/auxfn.R')
source('modules/downPlot.R')
source('modules/tabHist.R')
source('modules/tabHier.R')
source('modules/tabHierSparse.R')
source('modules/tabBayClust.R')
source('modules/tabClValid.R')
